// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "45a48ce4-c8bf-4743-9faa-d761436bc116");
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1665965654);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1665965638);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1665965774);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1665965659);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{9dafe756-91a6-4717-b171-c0da2c07c2ef}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.engagement.ctrlTab.has-used", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1665965624);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 128);
user_pref("browser.newtabpage.activity-stream.feeds.topsites", false);
user_pref("browser.newtabpage.activity-stream.impressionId", "{43606105-cd2f-4264-a4f8-eec94a904e00}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "google");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://google.com\",\"label\":\"@google\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1665965630);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1665965682580");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1665967470580");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1665965640715");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1665987240715");
user_pref("browser.search.region", "BR");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20220912135840");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1665965867");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage", "file:///etc/firefox/startpage/index.html");
user_pref("browser.startup.homepage_override.buildID", "20220912135840");
user_pref("browser.startup.homepage_override.mstone", "102.3.0");
user_pref("browser.startup.lastColdStartupCheck", 1665965867);
user_pref("browser.theme.content-theme", 0);
user_pref("browser.theme.toolbar-theme", 0);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"ublock0_raymondhill_net-browser-action\",\"addon_darkreader_org-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\",\"ublock0_raymondhill_net-browser-action\",\"addon_darkreader_org-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1665965634802");
user_pref("distribution.iniFile.exists.appversion", "102.3.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "BR");
user_pref("dom.push.userAgentID", "ae531b9d3ed04fe7aeb3507b84298b67");
user_pref("extensions.activeThemeID", "firefox-compact-dark@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20220912135840");
user_pref("extensions.lastAppVersion", "102.3.0");
user_pref("extensions.lastPlatformVersion", "102.3.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/theme");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.ui.sitepermission.hidden", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.addon@darkreader.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"36c3964f-6ce8-42b5-bd8c-67acf52f3d2b\",\"formautofill@mozilla.org\":\"1c17cd57-b30e-4b1c-b87d-da1ab1790b4e\",\"pictureinpicture@mozilla.org\":\"3b972bac-2686-40a5-821a-73496de8d90f\",\"screenshots@mozilla.org\":\"467efce9-cb22-4470-a29f-e6065d213010\",\"webcompat-reporter@mozilla.org\":\"41cd9b8e-947a-40fd-8941-8c0864933524\",\"webcompat@mozilla.org\":\"d4d734c2-2517-4de4-8755-8066bc58ce9e\",\"default-theme@mozilla.org\":\"90c42d5f-ef01-49ad-97c4-367965230f98\",\"addons-search-detection@mozilla.com\":\"1db21781-79c6-49fa-a3c3-c62e0b86bc26\",\"google@search.mozilla.org\":\"c657bbc2-4082-4b12-8802-b8b609cca344\",\"amazondotcom@search.mozilla.org\":\"f488077a-b7a2-4e62-83bd-ac1e503d0b89\",\"wikipedia@search.mozilla.org\":\"5c3999a9-4adc-45db-a827-8a08cce40b33\",\"bing@search.mozilla.org\":\"17b0214b-b89d-40b1-8324-1e00465fb4d3\",\"ddg@search.mozilla.org\":\"7e5ef9a1-d8fe-411a-bd2a-a9cb4531ec1d\",\"firefox-compact-dark@mozilla.org\":\"4d2d5192-35dd-4c0e-9f59-2d9a78787819\",\"uBlock0@raymondhill.net\":\"3382c0dd-24ef-4527-bb98-54357816fc0e\",\"addon@darkreader.org\":\"af7a0c8d-16f4-4f6c-b72a-344d773d5e6e\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1665965634);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.predictor.enabled", false);
user_pref("network.prefetch-next", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pref.browser.homepage.disable_button.current_page", false);
user_pref("pref.privacy.disable_button.cookie_exceptions", false);
user_pref("privacy.donottrackheader.enabled", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "e84f4f56-d314-48b1-8899-48f32a8b747f");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("toolkit.startup.last_success", 1665965841);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20220912135840");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
